apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-api-locations
  name: udaconnect-api-locations
spec:
  ports:
  - name: "5001"
    port: 5001
    targetPort: 5001
    nodePort: 30001
  selector:
    service: udaconnect-api-locations
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-api-locations
  name: udaconnect-api-locations
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-api-locations
  template:
    metadata:
      labels:
        service: udaconnect-api-locations
    spec:
      containers:
      - image: fthiagomedeiros/location-event-service-api:latest
        name: location-event-api-container
        imagePullPolicy: Always
        env:
        - name: KAFKA_URL
          valueFrom:
            configMapKeyRef:
              name: config-location-event-map
              key: KAFKA_URL
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: config-location-event-map
              key: KAFKA_TOPIC
        - name: PYTHONUNBUFFERED
          value: '0'
      restartPolicy: Always   