apiVersion: v1
kind: ConfigMap
data:
  DB_USERNAME: "ct_admin"
  DB_NAME: "geoconnections"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  PERSON_SERVICE_ENDPOINT: "http://udaconnect-api-persons:5002/"
metadata:
  name: db-env