apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-persons-api
  name: udaconnect-persons-api
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30001
  selector:
    service: udaconnect-persons-api
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-grpc-person-api
  name: udaconnect-grpc-person-api
spec:
  ports:
  - name: "5002"
    port: 5002
    targetPort: 5002
    nodePort: 30001
  selector:
    service: udaconnect-grpc-person-api
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-grpc-service-api
  name: udaconnect-grpc-service-api
spec:
  ports:
  - name: "5001"
    port: 5001
    targetPort: 5001
    nodePort: 30001
  selector:
    service: udaconnect-grpc-service-api
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-location-api
  name: udaconnect-location-api
spec:
  ports:
  - name: "5010"
    port: 5010
    targetPort: 5010
    nodePort: 30001
  selector:
    service: udaconnect-location-api
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-connection-api
  name: udaconnect-connection-api
spec:
  ports:
  - name: "5020"
    port: 5020
    targetPort: 5020
    nodePort: 30001
  selector:
    service: udaconnect-connection-api
  type: NodePort
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-api
  name: udaconnect-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-api
  template:
    metadata:
      labels:
        service: udaconnect-api
    spec:
      containers:
      - image: udacity/nd064-udaconnect-api:latest
        name: udaconnect-api
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
