apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-api-connection
  name: udaconnect-api-connection
spec:
  ports:
  - name: "5003"
    port: 5003
    targetPort: 5003
    nodePort: 30003
  selector:
    service: udaconnect-api-connection
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-api-connection
  name: udaconnect-api-connection
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-api-connection
  template:
    metadata:
      labels:
        service: udaconnect-api-connection
    spec:
      containers:
      - image: madaicol/nd064-udaconnect-api-connection:v1.0
        name: udaconnect-api-connection
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
