apiVersion: v1
kind: Service
metadata:
  labels:
    service: api-locations
  name: api-locations
spec:
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  selector:
    service: api-locations
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: api-locations
  name: api-locations
spec:
  replicas: 1
  selector:
    matchLabels:
      service: api-locations
  template:
    metadata:
      labels:
        service: api-locations
    spec:
      containers:
      - image: madaicol/udaconnect-api_locations:v1.1
        name: location-processor-container
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: KAFKA_URL
          valueFrom:
            configMapKeyRef:
              name: configuration-map
              key: KAFKA_URL
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: configuration-map
              key: KAFKA_TOPIC
        - name: PYTHONUNBUFFERED
          value: '0'
      restartPolicy: Always
